//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTareasWeb.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlDeTareasEntities : DbContext
    {
        public ControlDeTareasEntities()
            : base("name=ControlDeTareasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DETALLE_TAREA> DETALLE_TAREA { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<ESTADO> ESTADO { get; set; }
        public DbSet<FLUJO> FLUJO { get; set; }
        public DbSet<PROCESO> PROCESO { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<TAREA> TAREA { get; set; }
        public DbSet<UNIDAD> UNIDAD { get; set; }
    }
}
