//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTareasWeb.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ControlDeTareasEntities : DbContext
    {
        public ControlDeTareasEntities()
            : base("name=ControlDeTareasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DETALLE_TAREA> DETALLE_TAREA { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<ESTADO> ESTADO { get; set; }
        public DbSet<FLUJO> FLUJO { get; set; }
        public DbSet<PROCESO> PROCESO { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<TAREA> TAREA { get; set; }
        public DbSet<UNIDAD> UNIDAD { get; set; }
    
        public virtual int CT_CREATE_PROCESO(Nullable<decimal> iD_PROCESO, Nullable<decimal> iD_ESTADO_PRO, Nullable<decimal> iD_EMPRESA_PRO, string nOMBRE_PROCESO, Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_TERMINO)
        {
            var iD_PROCESOParameter = iD_PROCESO.HasValue ?
                new ObjectParameter("ID_PROCESO", iD_PROCESO) :
                new ObjectParameter("ID_PROCESO", typeof(decimal));
    
            var iD_ESTADO_PROParameter = iD_ESTADO_PRO.HasValue ?
                new ObjectParameter("ID_ESTADO_PRO", iD_ESTADO_PRO) :
                new ObjectParameter("ID_ESTADO_PRO", typeof(decimal));
    
            var iD_EMPRESA_PROParameter = iD_EMPRESA_PRO.HasValue ?
                new ObjectParameter("ID_EMPRESA_PRO", iD_EMPRESA_PRO) :
                new ObjectParameter("ID_EMPRESA_PRO", typeof(decimal));
    
            var nOMBRE_PROCESOParameter = nOMBRE_PROCESO != null ?
                new ObjectParameter("NOMBRE_PROCESO", nOMBRE_PROCESO) :
                new ObjectParameter("NOMBRE_PROCESO", typeof(string));
    
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_TERMINOParameter = fECHA_TERMINO.HasValue ?
                new ObjectParameter("FECHA_TERMINO", fECHA_TERMINO) :
                new ObjectParameter("FECHA_TERMINO", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CT_CREATE_PROCESO", iD_PROCESOParameter, iD_ESTADO_PROParameter, iD_EMPRESA_PROParameter, nOMBRE_PROCESOParameter, fECHA_INICIOParameter, fECHA_TERMINOParameter);
        }
    }
}
