//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTareasWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_TAREA
    {
        public int ID_DETALLE { get; set; }
        public Nullable<int> ID_RUT_DETALLE { get; set; }
        public Nullable<int> ID_TAREA_DETALLE { get; set; }
        public Nullable<short> ID_ESTADO_DETALLE { get; set; }
        public string JUSTIFICACION { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual TAREA TAREA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
    }
}
