//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTareasWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int ID_RUT { get; set; }
        public Nullable<int> ID_EMPRESA_EMP { get; set; }
        public Nullable<int> ID_ROL_EMP { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public string NOMBRE_EMP { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
