//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTareasWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO
    {
        public ESTADO()
        {
            this.PROCESO = new HashSet<PROCESO>();
            this.UNIDAD = new HashSet<UNIDAD>();
            this.TAREA = new HashSet<TAREA>();
        }
    
        public short ID_ESTADO { get; set; }
        public string NOMBRE_ESTADO { get; set; }
    
        public virtual ICollection<PROCESO> PROCESO { get; set; }
        public virtual ICollection<UNIDAD> UNIDAD { get; set; }
        public virtual ICollection<TAREA> TAREA { get; set; }
    }
}
