//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTareasWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLUJO
    {
        public int ID_FLUJO { get; set; }
        public Nullable<int> ID_UNIDAD_FLUJO { get; set; }
        public Nullable<int> ID_TAREA_FLUJO { get; set; }
    
        public virtual UNIDAD UNIDAD { get; set; }
        public virtual TAREA TAREA { get; set; }
    }
}
