//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTareasWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        public TAREA()
        {
            this.DETALLE_TAREA = new HashSet<DETALLE_TAREA>();
            this.FLUJO = new HashSet<FLUJO>();
        }
    
        public int ID_TAREA { get; set; }
        public Nullable<int> ID_UNIDAD_TAREA { get; set; }
        public Nullable<short> ID_ESTADO_TAREA { get; set; }
        public Nullable<int> ID_EMPRESA_TAREA { get; set; }
        public string NOMBRE_TAREA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
    
        public virtual ICollection<DETALLE_TAREA> DETALLE_TAREA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<FLUJO> FLUJO { get; set; }
        public virtual UNIDAD UNIDAD { get; set; }
    }
}
