//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDeTareasWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDAD
    {
        public UNIDAD()
        {
            this.FLUJO = new HashSet<FLUJO>();
            this.TAREA = new HashSet<TAREA>();
        }
    
        public int ID_UNIDAD { get; set; }
        public Nullable<int> ID_PROCESO_UNI { get; set; }
        public Nullable<short> ID_ESTADO_UNI { get; set; }
        public Nullable<int> ID_EMPRESA_UNI { get; set; }
        public string NOMBRE_UNIDAD { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<FLUJO> FLUJO { get; set; }
        public virtual PROCESO PROCESO { get; set; }
        public virtual ICollection<TAREA> TAREA { get; set; }
    }
}
